# docker-compose.dev.yml
services:
  backend:
    image: junseonpark/passtival-spring
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passtival-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAKAO_CLIENT_NAME=${KAKAO_CLIENT_NAME}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_AUTHORIZATION_GRANT_TYPE=${KAKAO_AUTHORIZATION_GRANT_TYPE}
      - KAKAO_SCOPE=${KAKAO_SCOPE}
      - KAKAO_AUTHORIZATION_URI=${KAKAO_AUTHORIZATION_URI}
      - KAKAO_TOKEN_URI=${KAKAO_TOKEN_URI}
      - KAKAO_USER_INFO_URI=${KAKAO_USER_INFO_URI}
      - KAKAO_USER_NAME_ATTRIBUTE=${KAKAO_USER_NAME_ATTRIBUTE}
      - MATCHING_CRON=${MATCHING_CRON}
      - MATCHING_CLEANUP_CRON=${MATCHING_CLEANUP_CRON}
      - MATCHING_BLOCK=${MATCHING_BLOCK}
    networks:
      - backend

  db:
    image: 'mysql:8.0'
    container_name: passtival-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=passtival-db
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend: