global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Spring Boot 애플리케이션 메트릭
  - job_name: 'passtival-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'backend:8080' ]
    scrape_timeout: 15s

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]