spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: ${KAKAO_CLIENT_NAME}
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            scope: ${KAKAO_SCOPE}
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false # SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false # SQL 포맷팅 비활성화
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # Hibernate SQL 로그 비활성화
        use_sql_comments: false # SQL 주석 비활성화
  matching:
    cron: ${MATCHING_CRON}
    cleanup-cron: ${MATCHING_CLEANUP_CRON}

swagger:
  server:
    url: ${SWAGGER_SERVER_URL}
    description: "운영 서버"

logging:
  level:
    root: error
    com.passtival.backend: error

server:
  # Nginx 등 리버스 프록시의 X-Forwarded-* 헤더를 신뢰하여 HTTPS 스킴을 반영
  forward-headers-strategy: native

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

admin:
  seed-key: ${ADMIN_SEED_KEY}
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}

seed:
  auth-keys-path: "file:/app/deploy/authentication-keys.xlsx"

frontend:
  login-url: ${FRONTEND_LOGIN_URL}
  login-fail-url: ${FRONTEND_LOGIN_FAIL_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: "never"
      probes:
        enabled: true
      status:
        http-mapping:
          down: 503
          out-of-service: 503
      validate-group-membership: true

      group:
        readiness:
          include: "readinessState,db,diskSpace"
        liveness:
          include: "livenessState"
        capacity:
          include: "cpuHealth,memoryHealth"
          status:
            order: "fatal,down,out-of-service,up,unknown"
            http-mapping:
              fatal: 200