spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 배포 시엔 validate or none
    show-sql: false # SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false # SQL 포맷팅 비활성화
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # Hibernate SQL 로그 비활성화
        use_sql_comments: false # SQL 주석 비활성화

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org.hibernate.sql: off # Hibernate SQL 로그 비활성화
    org.hibernate.type.descriptor.sql.BasicBinder: off
    # 애플리케이션 로그만 유지
    com.passtival.backend: info

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}


