spring:
  profiles:
    active: dev # 기본값 : dev, 배포 시 prod로 오버라이드
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}