spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: ${KAKAO_CLIENT_NAME}
            client-authentication-method: client_secret_post
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
            scope: ${KAKAO_SCOPE}
        provider:
          kakao:
            authorization-uri: ${KAKAO_AUTHORIZATION_URI}
            token-uri: ${KAKAO_TOKEN_URI}
            user-info-uri: ${KAKAO_USER_INFO_URI}
            user-name-attribute: ${KAKAO_USER_NAME_ATTRIBUTE}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false # SQL 로그 비활성화
    properties:
      hibernate:
        format_sql: false # SQL 포맷팅 비활성화
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: false # Hibernate SQL 로그 비활성화
        use_sql_comments: false # SQL 주석 비활성화

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  thymeleaf:
    cache: true

swagger:
  server:
    url: ${SWAGGER_SERVER_URL}
    description: "운영 서버"

logging:
  level:
    root: error
    com.passtival.backend: info

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}

app:
  admin:
    seed-key: ${APP_ADMIN_SEED_KEY}
    login-id: ${ADMIN_INITIAL_LOGIN_ID}
    auth-key: ${ADMIN_INITIAL_AUTH_KEY}