spring:
  datasource:
    url: jdbc:mysql://passtival-db:3306/passtival-db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 개발 중에는 update, 배포 시엔 validate or none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.passtival.backend: debug

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION}


