spring:
  profiles:
    active: prod # 기본값 : dev, 배포 시 prod로 오버라이드
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    s3:
      bucket: ${AWS_S3_BUCKET}
      presigned-url:
        expiration-minutes: 10 # presigned URL 만료 시간 (분 단위)

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}